### ISSUE TITLE
How do I use this library, insufficient documentation ?

### ISSUE THREAD

**Issue by ThadeusAjayi** [RameshBhupathi/ImagePicker-OLX#1]
There seems to be less documentation on how to use this library, or is this an example project ?

**Comment by RameshBhupathi** [comment]
This is an example Project @ThadeusAjayi

**Comment by ThadeusAjayi** [comment]
Thanks for the prompt reply.

**Comment by RameshBhupathi** [comment]
Please give a star if u feel helpful @ThadeusAjayi
